[workspace]
authors = ["Lucas Graybuck <lucasg@alleninstitute.org>"]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
name = "t-cell_vrd_deg"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
dash = "==3.1.0"
dash-ag-grid = ">=35.3.0,<36"
dash-bootstrap-components = ">=2.0.4,<3"
dash-iconify = ">=0.1.2,<0.2"
jsonschema = ">=4.26.0,<5"
numpy = ">=2.5.1,<3"
polars = ">=1.43.1,<2"
plotly = ">=6.9.0,<7"
mygene = { version = ">=3.2.2,<4", channel = "bioconda" }
