[project]
name = "sc-deg-explorer"
version = "0.1.0"
description = "Single-Cell DEG explorer project template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "dash==3.1.0",
  "dash-ag-grid==32.3.4",
  "dash-bootstrap-components==2.0.4",
  "dash-iconify",
  "jsonschema",
  "mygene",
  "numpy",
  "polars==1.37.1",
  "plotly==6.5.2",
  "allen-dash-modules",
]

[tool.uv.workspace]
members = [
    "libs/allen_dash_modules",
]

[tool.uv.sources]
allen-dash-modules = { workspace = true }
